# Generated by Django 3.0.7 on 2020-06-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_tweet_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tweet',
            name='replying_to',
            field=models.ForeignKey(blank=True, help_text='This tweet is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter_app.Tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='video',
            field=models.FileField(blank=True, help_text='Video for the tweet', null=True, upload_to='tweet_media/videos/'),
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for a tweet', upload_to='tweet_media/images/')),
                ('tweet', models.ForeignKey(help_text='Tweet the image belongs to', on_delete=django.db.models.deletion.CASCADE, to='twitter_app.Tweet')),
            ],
        ),
    ]
