# Generated by Django 3.0.7 on 2020-06-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_auto_20200623_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='tweet',
            field=models.ForeignKey(help_text='Tweet the image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='twitter_app.Tweet'),
        ),
    ]
