# Generated by Django 3.0.7 on 2020-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0006_auto_20200629_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_retweet',
            field=models.BooleanField(default=False, help_text='Whether the tweet is a retweet (If it is, replying_to is the tweet being retweeted)'),
        ),
    ]
